services:
  redis:
    container_name: redis-stack-dev
    image: redis/redis-stack:7.4.0-v5
    restart: always
    ports:
      - '6379:6379'
    command: redis-stack-server --save 20 1 --loglevel warning --requirepass aa
    volumes: 
      - redis-dev:/data
volumes:
  redis-dev:

  