services:
  redis:
    container_name: redis-dev
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass aa
    volumes: 
      - redis-dev:/data
volumes:
  redis-dev: